# Config file for labeler to auto label PRs
documentation:
  - README.md
  - docs/**/*.md

template views:
  - views/**/*

config:
  - config/**/*
  - models/*
  - models/**/*

db:
  - db/**/*
  - models/**/*

UI/UX:
  - public/**/*.css
  - public/**/*.html

automation:
  - .github/**/*.yml

npm packages:
  - src/package.json
  - src/package-lock.json

models:
  - models/*
  - models/**/*

public:
  - public/*
  - public/**/*

routes:
  - routes/*
  - routes/**/*
