# Config file for labeler to auto label PRs
documentation:
  - README.md
  - docs/*

template views:
  - views/*

config:
  - config/*

db:
  - db/*

UI/UX:
  - src/**/*.css
  - views/*

automation:
  - src/**/*.yml

npm packages:
  - src/package.json
  - src/package-lock.json
